server {  
  listen 80;

  server_name yurykuznetsov.us;

  location / {
    proxy_pass http://ui:3000;
    proxy_connect_timeout 5s;
    proxy_read_timeout 10s;
  }

  location /api {
    proxy_pass http://api:3001;
    proxy_connect_timeout 5s;
    proxy_read_timeout 10s;
  }  
}
